#!/bin/sh
# usage update-secret key value description

aws secretsmanager create-secret --name "${1}" --secret-string "${2}" --description "${3}" &> /dev/null 2>&1
aws secretsmanager put-secret-value --secret-id "${1}" --secret-string "${2}"